'use strict';
window.spotifyAuth=(()=>{const CLIENT_ID=window.STREAMLAB_SPOTIFY_CLIENT_ID||'';const redirect=location.origin+location.pathname.replace(/[^/]*$/,'');const storageKey='sl_spotify_token';const key='sl_pkce';const stateKey='sl_oauth_state';let token=null,catalogBlocked=false;try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(saved&&saved.expires>Date.now())token=saved.value}catch{}const ready=()=>Boolean(token);const available=()=>ready()&&!catalogBlocked;const configured=()=>Boolean(CLIENT_ID)&&location.protocol==='https:';
function b64(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'')}
async function connect(){if(!configured())throw Error('Primero configura tu Client ID de Spotify y publica la web con HTTPS.');const verifier=b64(crypto.getRandomValues(new Uint8Array(64))),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)),state=b64(crypto.getRandomValues(new Uint8Array(24)));sessionStorage.setItem(key,verifier);sessionStorage.setItem(stateKey,state);const url=new URL('https://accounts.spotify.com/authorize');url.search=new URLSearchParams({response_type:'code',client_id:CLIENT_ID,redirect_uri:redirect,code_challenge_method:'S256',code_challenge:b64(new Uint8Array(digest)),state}).toString();location.assign(url.href)}
async function handleCallback(){const url=new URL(location.href),code=url.searchParams.get('code'),error=url.searchParams.get('error'),originalState=url.searchParams.get('state');if(!code&&!error)return;url.searchParams.delete('code');url.searchParams.delete('state');url.searchParams.delete('error');history.replaceState(null,'',url);if(error)throw Error('Spotify no autorizó la conexión: '+error);const verifier=sessionStorage.getItem(key),state=sessionStorage.getItem(stateKey);sessionStorage.removeItem(key);sessionStorage.removeItem(stateKey);if(!verifier||!state||state!==originalState)throw Error('La conexión con Spotify no pudo verificarse. Inténtalo de nuevo.');
const body=new URLSearchParams({client_id:CLIENT_ID,grant_type:'authorization_code',code,redirect_uri:redirect,code_verifier:verifier});const res=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!res.ok)throw Error('Spotify rechazó la autorización. Comprueba la URL de retorno registrada.');const data=await res.json();token=data.access_token;sessionStorage.setItem(storageKey,JSON.stringify({value:token,expires:Date.now()+(data.expires_in-60)*1000}));return true}
async function request(path){if(!available())throw Error('El catálogo de Spotify no está disponible.');const res=await fetch('https://api.spotify.com/v1'+path,{headers:{Authorization:'Bearer '+token}});if(res.status===401){token=null;sessionStorage.removeItem(storageKey);throw Error('La conexión con Spotify caducó. Vuelve a conectarla.')}if(res.status===403){catalogBlocked=true;throw Error('Spotify rechazó el acceso al catálogo (403). Comprueba los usuarios autorizados y los requisitos de tu app en Spotify for Developers.')}if(res.status===429)throw Error('Spotify limitó temporalmente las búsquedas. Inténtalo en unos minutos.');if(!res.ok)throw Error('Spotify no pudo cargar su catálogo (error '+res.status+').');return res.json()}
async function searchArtists(name){const data=await request('/search?'+new URLSearchParams({q:name,type:'artist',limit:'10',market:'EC'}));return data.artists?.items||[]}
async function paginate(path,maxPages){const items=[];for(let offset=0,page=0;page<maxPages;offset+=10,page++){const data=await request(path+(path.includes('?')?'&':'?')+new URLSearchParams({limit:'10',offset:String(offset),market:'EC'}));items.push(...(data.items||[]));if(!data.next||!data.items?.length)break}return items}
const artistAlbums=id=>paginate('/artists/'+encodeURIComponent(id)+'/albums?include_groups=album,single',8);
const albumTracks=id=>paginate('/albums/'+encodeURIComponent(id)+'/tracks',12);
async function findTrack(song){if(!ready())return null;const data=await request('/search?'+new URLSearchParams({q:`track:${song.track} artist:${song.artist}`,type:'track',limit:'10',market:'EC'}));const norm=s=>String(s||'').toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s*\(.*?\)|\s*\[.*?\]/g,'').replace(/[^a-z0-9]/g,'');const matches=(data.tracks?.items||[]).filter(x=>norm(x.name)===norm(song.track)&&x.artists.some(a=>norm(a.name)===norm(song.artist))&&Math.abs(x.duration_ms/1000-song.duration)<8);const albumMatches=matches.filter(x=>norm(x.album.name)===norm(song.album));const candidates=song.album?albumMatches:matches;if(candidates.length!==1)return null;return candidates[0].uri}
return {ready,available,configured,connect,handleCallback,findTrack,searchArtists,artistAlbums,albumTracks}})();
